#ifndef NOP_UNDEF_VECTOR_MACRO_DEFINITIONS_HPP /* Begin undef macro definitions header file */
#define NOP_UNDEF_VECTOR_MACRO_DEFINITIONS_HPP 1

#undef __NOP_VECTOR_MAX_SIZE__
#undef __NOP_VECTOR_GET_ALLOCATOR__
#undef __NOP_VECTOR_SHRINK_TO_FIT__
#undef __NOP_VECTOR_PUSH_BACK__
#undef __NOP_VECTOR_POP_BACK__
#undef __NOP_VECTOR_TO_STRING__
#undef __NOP_VECTOR__
#undef __NOP_VECTOR_ITERATOR__
#undef __NOP_VECTOR_PROXY_ITERATOR__
#undef __NOP_VECTOR_CONST_ITERATOR__
#undef __NOP_VECTOR_SIZE_TYPE__
#undef __NOP_VECTOR_VALUE_TYPE__
#undef __NOP_VECTOR_ALLOCATOR_TYPE__
#undef __NOP_VECTOR_DIFFERENCE_TYPE__
#undef __NOP_VECTOR_CONST_REFERENCE__
#undef __NOP_VECTOR_CONST_POINTER__
#undef __NOP_VECTOR_POINTER__
#undef __NOP_VECTOR_REFERENCE__

#endif /* End undef macro definitions header file */
